name: Build javascript project
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build javascript
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1
        with: 
          output: './test.app.bom.xml'
      
      - name: Create SBOM step
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
            path: './frontend/'
            output: './bom_directory/test.app.bom.xml'
    
  dependencyCheck:
    runs-on: ubuntu-latest
    name: Build dependency-check
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        id: jdk-8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        id: build
        run: |
          ./gradlew build
